windowrule = float, class:file_progress
windowrule = float, class:confirm
windowrule = float, class:dialog
windowrule = float, class:download
windowrule = float, class:notification
windowrule = float, class:error
windowrule = float, class:splash
windowrule = float, class:confirmreset
windowrule = float, class:title:Open File
windowrule = float, class:title:branchdialog
windowrule = float, class:Lxappearance
windowrule = float, class:Rofi
windowrule = animation none,class:Rofi
windowrule = float, class:viewnior
windowrule = float, class:Viewnior
windowrule = float, class:feh
windowrule = float, class:pavucontrol-qt
windowrule = float, class:pavucontrol
windowrule = float, class:file-roller
windowrule = float, title:DevTools
windowrule = fullscreen, class:wlogout
windowrule = float, title:wlogout
windowrule = fullscreen, title:wlogout
windowrule = idleinhibit focus, class:mpv
windowrule = float, title:^(Media viewer)$
windowrule = float, title:^(Volume Control)$
windowrule = float, title:^(Picture-in-Picture)$
windowrule = size 800 600, title:^(Volume Control)$
windowrule = move 75 44%, title:^(Volume Control)$
windowrule = float, title:^(Firefox — Sharing Indicator)$
windowrule = float, title:^(Calculator)$
windowrule = float, title:^(Progress)$
windowrule = float, title:^(zenity)$
windowrule = float, title:^(video0)$
windowrule = float, class:yad
windowrule = float, class:qt5ct
windowrule = float, class:qt6ct
windowrule = float, class:floating_shell_portrait
windowrule = float, class:blueman-manager
windowrule = float, class:xsensors
windowrule = float, class:image-roll
windowrulev2 = float,class:^(qalculate-qt)$,title:^(Qalculate!)$

windowrulev2 = bordersize 0, floating:0, onworkspace:w[tv1]
windowrulev2 = rounding 0, floating:0, onworkspace:w[tv1]
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]




# firefox Picture-in-Picture
windowrule = float,class:^(firefox)$,title:^(Picture-in-Picture)$
windowrule = pin,class:^(firefox)$,title:^(Picture-in-Picture)$

# firefox figma micro indicator
windowrule = float,class:^(firefox)$,title:^(Firefox — Sharing Indicator)$

# Telegram media viewer
windowrule = float,class:^(org.telegram.desktop)$,title:^(Media viewer)$
windowrule = center,class:^(org.telegram.desktop)$,title:^(Media viewer)$
windowrule = monitor 1,class:^(org.telegram.desktop)$,title:^(Media viewer)$

# common modals
windowrule = float,title:^(Open)$
windowrule = float,title:^(Choose Files)$
windowrule = float,title:^(Save As)$
windowrule = float,title:^(Confirm to replace files)$
windowrule = float,title:^(File Operation Progress)$

# taskwarrior
windowrule = center,class:^(task-floating)$
windowrule = float,class:^(task-floating)$
windowrule = dimaround,class:^(task-floating)$
windowrule = noborder,class:^(task-floating)$

windowrule = center,class:pavucontrol
windowrule = float,class:file-roller

windowrulev2 = dimaround,class:^(jetbrains-phpstorm)$,title:^(License )
windowrulev2 = float,class:^(jetbrains-phpstorm)$,title:^(License )
windowrulev2 = center,class:^(jetbrains-phpstorm)$,title:^(License )
