# ~/.config/hypr/hyprpaper.conf

splash = false

### Laptop ###
wallpaper {
    monitor = eDP-1
    path = /home/drsh4dow/Projects/dotconfig/backgrounds/59.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/drsh4dow/Projects/dotconfig/backgrounds/59.png
    fit_mode = cover
}

### Desktop ###
# wallpaper {
#     monitor = DP-2
#     path = /home/drsh4dow/Projects/dotconfig/backgrounds/59.png
#     fit_mode = cover
# }
#
wallpaper {
    monitor = DP-3
    path = /home/drsh4dow/Projects/dotconfig/backgrounds/vertical.jpg
    fit_mode = cover
}
