[general]
; Low-latency defaults for Steam games launched with gamemoderun.
reaper_freq=5
desiredgov=performance
igpu_desiredgov=powersave
igpu_power_threshold=-1
softrealtime=auto
renice=10
ioprio=0
inhibit_screensaver=1

[custom]
start=/home/drsh4dow/Projects/dotconfig/scripts/gamemode-start
end=/home/drsh4dow/Projects/dotconfig/scripts/gamemode-end
